Added isLargeForContrastRatio
material-foundation/material-roboto-font-loader-ios pull request #11
Opened 2017-03-01 20:30 UTC by randallli

So we can consider medium fonts large when larger than 14pts

2017-03-01 20:36 UTC, randallli commented
related to https://github.com/material-components/material-components-ios/pull/1232

2017-03-01 20:50 UTC, ajsecord requested changes

2017-03-01 20:50 UTC, ajsecord commented on src/MDFRobotoFontLoader.h
> + */
Please link out to something (the W3C spec?) that explains what this is all about.

2017-03-01 20:56 UTC, randallli commented
added link

2017-03-01 22:38 UTC, randallli commented
dropping in favor of https://github.com/material-foundation/material-text-accessibility-ios/pull/14

2017-03-07 15:56 UTC, ajsecord approved these changes

2017-03-07 20:12 UTC, ianegordon approved these changes

2017-03-07 20:12 UTC, merged